### ISSUE TITLE
App Crashes while saving the video

### ISSUE THREAD

**Issue by namespace7** [Truiton/ScreenCapture#4]
The application Crashes while Saving the Video If we rotate screen(Landscape,Portrait ) while the screen has been capturing !
If i start recording the screen while the phone is in landscape mode and end up video recording,while the phone is in portrait mode,The Application crashes!
Here it the log !

**2019-05-03 17:55:55.993 24224-24229/com.truiton.screencapture I/zygote: Increasing code cache capacity to 128KB
2019-05-03 17:55:56.048 24224-24224/com.truiton.screencapture E/MediaRecorder: stop called in an invalid state: 1
2019-05-03 17:55:56.048 24224-24224/com.truiton.screencapture D/AndroidRuntime: Shutting down VM
2019-05-03 17:55:56.052 24224-24224/com.truiton.screencapture E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.truiton.screencapture, PID: 24224
    java.lang.IllegalStateException
        at android.media.MediaRecorder.stop(Native Method)
        at com.truiton.screencapture.MainActivity.onToggleScreenShare(MainActivity.java:129)
        at com.truiton.screencapture.MainActivity$1.onClick(MainActivity.java:99)
        at android.view.View.performClick(View.java:6256)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
**

**Comment by namespace7** [comment]
I have solved the issue by adding the this line of Code

> setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

The allows application to start capturing and ending the screen in One mode
